### PR TITLE
Adds pep585-upgrade

### PR DESCRIPTION
**Pull request by sobolevn**
https://github.com/snok/pep585-upgrade

### CODE REVIEW

**Review by orsinium — APPROVED** [review]
Great finding, I'll give it a try 👍🏿

**Comment by orsinium** [comment]
Huh, no pypi release, no friendly way to run.

**Comment by sobolevn** [comment]
> no pypi release
It is because it is oriented for Python's `pre-commit` ecosystem. It does not use PyPI, but instead it uses YAML definitions.

> no friendly way to run

That's a common problem for all `pre-commit` plugins 😞 
See https://github.com/snok/pep585-upgrade#running-this-once-on-my-codebase

**Comment by orsinium** [comment]
Yes, I saw the docs. Oh well, probably it will never be properly released "by design". Let's merge it as-is then. Thank you :)

**Comment by hugovk** [comment]
> That's a common problem for all `pre-commit` plugins 😞

As it happens, many of the plugins by the author of pre-commit are on PyPI and runnable as standalone commands, for example https://github.com/asottile/pyupgrade

But in this case, it does look by design.

**Pull request merged**
