### PR TITLE
feat: Add a version with Activity Badges

### PR DESCRIPTION
**Pull request by 34j**
I did this because I found that there were many unmaintained packages in the list.  I don't know if you will merge them or not, but I am trying to send a Pull Request. Running `run.py` will update the list.

### CODE REVIEW

**Comment by orsinium** [comment]
Thank you for your contributions! I appreciate that :) However, I'm more inclined to currently reject the idea for several reasons:

1. If you want to make sure repos aren't dead, there are already ready-to-use solutions like [awesome-lint](https://github.com/sindresorhus/awesome-lint). I just never bothered.
2. Table layout isn't mobile-friendly, that's why web moved from them a long time ago.
3. I find such metrics harmful and misleading. If a project didn't get any updates for a long time, it doesn't mean it is broken or unmaintained. Some projects are simple and "just work", and so don't need active maintenance.
4. There are bots like [dependabot](https://github.com/dependabot) that create activity and commits in the repo without doing anything useful for me as a user. Such repos will appear more active but it doesn't mean there are better.

That said, if you see projects that are archived, broken, or unmaintained (in terms that they have important PRs without reviews for years, not that they don't commit there daily), please, send a PR, I'll be glad to accept it. For instance, I see, thanks to your script, that `reindent.py` has been removed.

What do you think?

**Comment by 34j** [comment]
I think "harmful" is an overstatement, but this repository does not seem to be so active maintained, so I opened a PR. (Of course, I am not saying that the project is sane because it has commits, but rather that the lack of commits is a problem. Because such things rarely work in my experience.)

You could put it in a separate branch, etc, but if you dont like it you may close it. Thank you for your response.

**Comment by cleder** [comment]
I agree with Gram, reason being

- I use awesome-lint  and am +-0 on its use
-  tables and mobile is not a good match 
- I maintain projects (other topics though) where 3. and 4. applies.

An action that flags up archived projects would be helpful

**Comment by orsinium** [comment]
> An action that flags up archived projects would be helpful

Great idea! I'm open to contributions if you have something ready-to-use in mind. I can enable Actions for that occasion.

**Comment by orsinium** [comment]
> I think "harmful" is an overstatement, I opened this PR because this repository does not seem to be so actively maintained

Sorry for the misunderstanding. I mean not your contribution is harmful but harmful to show people these numbers. We shouldn't show a metric that artificially indicates some repos are better than others. I still appreciate your contribution, it's just having an "awesome" list requires to some extent one-man subjective vision of what is considered awesome, and I don't want the number of commits to be a decider for this. Don't let this one discourage you from future contributions ❤️

**Pull request closed without merging**
